# Generated by Django 2.0.3 on 2018-03-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0002_auto_20180330_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Notification')),
                ('description', models.TextField(default='')),
                ('img', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
