# Generated by Django 2.0.3 on 2018-04-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0004_auto_20180331_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='current_location',
            field=models.TextField(default='[]'),
        ),
    ]
