# Generated by Django 2.0.3 on 2018-04-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0006_auto_20180402_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='current_target',
            field=models.TextField(default='{"x": null, "y": null}'),
        ),
    ]
