# Generated by Django 2.0.3 on 2018-04-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0007_map_current_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='images_requested',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
