# Generated by Django 2.0.3 on 2018-03-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='boundariesEncoded',
        ),
        migrations.AddField(
            model_name='map',
            name='boundaries',
            field=models.TextField(default='{"boundaries":[]}'),
        ),
        migrations.AddField(
            model_name='map',
            name='currently_mapping',
            field=models.BooleanField(default=False),
        ),
    ]
