# Generated by Django 2.0.3 on 2018-03-31 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0003_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='currently_mapping',
        ),
        migrations.AddField(
            model_name='map',
            name='current_mode',
            field=models.IntegerField(choices=[(0, 'normal'), (1, 'mapping'), (2, 'patrol')], default=0),
        ),
        migrations.AddField(
            model_name='map',
            name='patrol_path',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='map',
            name='boundaries',
            field=models.TextField(default='[]'),
        ),
    ]
