# Generated by Django 2.0.3 on 2018-04-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0005_map_current_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='current_location',
            field=models.TextField(default='{"x": 0, "y": 0, "angle": 90}'),
        ),
    ]
